spring:
  datasource:
    username: user
    password: pw
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    platform: h2
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false #disable batch job executing on startup
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.simple: debug

